# -*- coding: utf-8 -*-
"""ulyanov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2Q4Idphb_hbkPkjAjkU42lL4sO6uytt
"""

import requests

apiKey = 'MbNWQfHAsg9gatULkp04nACdeqPBrJqihYNQSEWo'

def fetchMars():
  URL = "https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?"
  date = '2022-01-11'
  params = {
      'api_key':apiKey,
      'earth_date':date,
      'hd':'True'
  }
  response = requests.get(URL, params=params).json()
  ans = (response)
  return ans['photos'][:3]
fetchMars()

